-- Parent report links — shareable public URLs generated by admin for parents
-- No auth required to read; validated by token + expiry check
-- Applied via: Supabase Dashboard > SQL Editor

CREATE TABLE IF NOT EXISTS public.parent_links (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id  TEXT NOT NULL,
  invoice_id  TEXT DEFAULT NULL,
  token       UUID NOT NULL DEFAULT gen_random_uuid(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days'),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT parent_links_token_unique UNIQUE (token)
);

-- RLS
ALTER TABLE public.parent_links ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'parent_links' AND policyname = 'service_role_all'
  ) THEN
    CREATE POLICY "service_role_all" ON public.parent_links
      TO service_role USING (true) WITH CHECK (true);
  END IF;
END$$;
